name: Build msi installer

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v3

      # https://github.com/dotnet-campus/dotnetCampus.TagToVersion
      - name: Install dotnet tool
        run: dotnet tool install -g dotnetCampus.TagToVersion

      - name: Set tag to version  
        run: dotnet TagToVersion -t ${{ github.ref }} -f Version.props

      - name: Build
        run: dotnet build -c Release

      - name: Upload MSI to GitHub Releases
        id: upload-msi
        uses: softprops/action-gh-release@v1
        with:
          files: Installer/output/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.ref }}
          release_name: v${{ github.ref }}
          body: |
            Solidworks urdf msi installer v${{ github.ref }}.
          draft: true
          prerelease: true
